services:
  web:
    build: 
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    # command: python -m uvicorn core.asgi:application --host 0.0.0.0 --port 8000
    # command: python -m gunicorn core.asgi:application -k uvicorn_worker.UvicornWorker --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    # env_file:
    #   - .env
    # depends_on:
    #   - baseline_db
    networks:
      - chat_proj
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - chat_proj
  nginx:
    image: "nginx:latest"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "1337:80"
    depends_on:
      - web
    networks:
      - chat_proj

networks:
  chat_proj:

volumes:
  static_volume:
  media_volume: